default:
  image: 'maven:latest'

stages:
  - prepare
  - test
  - analysis

prepare:
  stage: prepare
  cache:
    key: m_m2
    paths:
      - .m2/repository/
  script:
    - mvn -v && java -version
    - mvn clean install -P skipTests -s settings.xml
  tags:
    - SHARE_MAVEN_JDK

tests:
  stage: test
  cache:
    key: m_m2
    policy: pull-push
    paths:
      - .m2/repository/
      - ./target
  script:
    - mvn clean install -P tests -s settings.xml
  artifacts:
    when: on_success
    paths:
      - target/failsafe/reports
      - target/surefire/reports
      - target/*.exec
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - SHARE_MAVEN_JDK

analysis:
  stage: analysis
  image: sonarsource/sonar-scanner-cli:latest
  cache:
    key: m_m2
    policy: pull
    paths:
      - ./target
  variables:
#    SONAR_TOKEN: '67296badea93b1a60d324330852a6256a1fec8b4'
#    SONAR_HOST_URL: "http://your-sonarqube-instance.org"
    GIT_DEPTH: 0
  script:
    - pwd & ls -l
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dproject.settings=sonar-project.properties -Dsonar.host.url=http://10.222.225.17:9000 -Dsonar.login=admin -Dsonar.password=admin
  tags:
    - SHARE_MAVEN_JDK
  only: master
