default:
  image: 'maven:latest'

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn -v && java -version
    - mvn clean install -P skipTests -s settings.xml
  tags:
    - SHARE_MAVEN_JDK

tests:
  stage: test
  script:
    - mvn clean install -P tests -s settings.xml
  tags:
    - SHARE_MAVEN_JDK