server:
  port: 8001

spring:
  application:
    name: spring-boot-test-ci
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
        auto: none
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org.hibernate.search: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG